find_package(Git QUIET)

set(CPACK_PACKAGE_VERSION_MAJOR)
set(CPACK_PACKAGE_VERSION_MINOR)
set(CPACK_PACKAGE_VERSION_PATCH)

if(GIT_FOUND)
	execute_process(COMMAND ${GIT_EXECUTABLE}
		describe --tags --dirty --exact-match --match "v*.*.*"
		WORKING_DIRECTORY ${PROJECT_SOURCE_DIR}
		RESULT_VARIABLE res
		OUTPUT_VARIABLE out
		ERROR_QUIET
		OUTPUT_STRIP_TRAILING_WHITESPACE)
	if(NOT res EQUAL 0)
		return()
	endif()

	if(${out} MATCHES "^v[0-9]+\\.[0-9]+\\.[0-9]+")
		string(REGEX MATCHALL "[0-9]+" VERSION_INFO ${out})
		list(GET VERSION_INFO 0 CPACK_PACKAGE_VERSION_MAJOR)
		list(GET VERSION_INFO 1 CPACK_PACKAGE_VERSION_MINOR)
		list(GET VERSION_INFO 2 CPACK_PACKAGE_VERSION_PATCH)
	endif()
endif()

